<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Recuro.Admin.Application\Recuro.Admin.Application.csproj" />
    <ProjectReference Include="..\Recuro.Admin.Domain\Recuro.Admin.Domain.csproj" />
  </ItemGroup>

</Project>
