// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recuro.Requisition.Infrastructure.Persistence;

#nullable disable

namespace Recuro.Requisition.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RequisitionDbContext))]
    [Migration("20261007204852_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("EventId", "Consumer")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("envelope");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at")
                        .HasFilter("processed_at IS NULL AND failed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.Requisition.Domain.JobDescriptions.JobDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("req_id");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("requisition_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<string>("_history")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("history");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Content", "Recuro.Requisition.Domain.JobDescriptions.JobDescription.Content#JobDescriptionContent", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Assessments")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("assessments");

                            b1.Property<string>("Benchmark")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("benchmark");

                            b1.Property<string>("Competencies")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("competencies");

                            b1.Property<string>("Experience")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("experience");

                            b1.Property<string>("Grade")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("grade");

                            b1.Property<string>("Location")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("location");

                            b1.Property<string>("MinQualification")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("min_qualification");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("purpose");

                            b1.Property<string>("ReportsTo")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("reports_to");

                            b1.Property<string>("Responsibilities")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("responsibilities");

                            b1.Property<string>("TeamSize")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("team_size");
                        });

                    b.HasKey("Id")
                        .HasName("pk_job_descriptions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_job_descriptions_tenant_id");

                    b.HasIndex("TenantId", "ReqId")
                        .HasDatabaseName("ix_job_descriptions_tenant_id_req_id");

                    b.HasIndex("TenantId", "RequisitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_job_descriptions_tenant_id_requisition_id");

                    b.ToTable("job_descriptions", (string)null);
                });

            modelBuilder.Entity("Recuro.Requisition.Domain.Requisitions.ManpowerRequisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigVersionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("config_version_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_name");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("req_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("StateChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_changed_at");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateOnly?>("TargetClosure")
                        .HasColumnType("date")
                        .HasColumnName("target_closure");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("WorkflowInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_instance_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Details", "Recuro.Requisition.Domain.Requisitions.ManpowerRequisition.Details#RequisitionDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Band")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("band");

                            b1.Property<string>("Department")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("department");

                            b1.Property<string>("Designation")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("designation");

                            b1.Property<string>("EmploymentType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("employment_type");

                            b1.Property<string>("Grade")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("grade");

                            b1.Property<DateOnly?>("JoiningDate")
                                .HasColumnType("date")
                                .HasColumnName("joining_date");

                            b1.Property<string>("Location")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("location");

                            b1.Property<string>("Nature")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("nature");

                            b1.Property<string>("OobJustification")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("oob_justification");

                            b1.Property<bool>("OutOfBudget")
                                .HasColumnType("boolean")
                                .HasColumnName("out_of_budget");

                            b1.Property<int>("Positions")
                                .HasColumnType("integer")
                                .HasColumnName("positions");

                            b1.Property<string>("Qualifications")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("qualifications");

                            b1.Property<string>("ReplacementReason")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("replacement_reason");

                            b1.Property<string>("ReportingManager")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("reporting_manager");

                            b1.Property<string>("SourcingChannels")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("sourcing_channels");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Route", "Recuro.Requisition.Domain.Requisitions.ManpowerRequisition.Route#ApprovalRoute", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ApproverRole")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("route_approver_role");

                            b1.Property<string>("Approving")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("route_approving");

                            b1.Property<string>("Initiating")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("route_initiating");

                            b1.Property<string>("Recommending")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("route_recommending");
                        });

                    b.HasKey("Id")
                        .HasName("pk_requisitions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_requisitions_tenant_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_requisitions_tenant_id_created_at");

                    b.HasIndex("TenantId", "ReqId")
                        .IsUnique()
                        .HasDatabaseName("ix_requisitions_tenant_id_req_id");

                    b.HasIndex("TenantId", "State")
                        .HasDatabaseName("ix_requisitions_tenant_id_state");

                    b.ToTable("requisitions", (string)null);
                });

            modelBuilder.Entity("Recuro.Requisition.Infrastructure.Persistence.ReqIdSequence", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<int>("LastValue")
                        .HasColumnType("integer")
                        .HasColumnName("last_value");

                    b.HasKey("TenantId", "Year")
                        .HasName("pk_req_id_sequences");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_req_id_sequences_tenant_id");

                    b.ToTable("req_id_sequences", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
