// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recuro.Careers.Infrastructure.Persistence;

#nullable disable

namespace Recuro.Careers.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CareersDbContext))]
    [Migration("20261008035028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("EventId", "Consumer")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("envelope");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at")
                        .HasFilter("processed_at IS NULL AND failed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.Careers.Domain.Applications.PublicApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("app_id");

                    b.Property<bool>("CandidateCreatedHere")
                        .HasColumnType("boolean")
                        .HasColumnName("candidate_created_here");

                    b.Property<string>("CandidateId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("candidate_id");

                    b.Property<string>("ClientKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_key");

                    b.Property<string>("DuplicateOf")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("duplicate_of");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("failure_code");

                    b.Property<Guid?>("FinalRejectedEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("final_rejected_event_id");

                    b.Property<string>("PipelineStage")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pipeline_stage");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("position");

                    b.Property<string>("PostingId")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("posting_id");

                    b.Property<string>("PublicStage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("public_stage");

                    b.Property<DateTimeOffset?>("RegretDeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("regret_delivered_at");

                    b.Property<DateOnly?>("RegretSendAt")
                        .HasColumnType("date")
                        .HasColumnName("regret_send_at");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("req_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_public_applications");

                    b.HasIndex("FinalRejectedEventId")
                        .HasDatabaseName("ix_public_applications_final_rejected_event_id")
                        .HasFilter("final_rejected_event_id IS NOT NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_public_applications_tenant_id");

                    b.HasIndex("TenantId", "AppId")
                        .IsUnique()
                        .HasDatabaseName("ix_public_applications_tenant_id_app_id")
                        .HasFilter("app_id IS NOT NULL");

                    b.HasIndex("TenantId", "ClientKey")
                        .IsUnique()
                        .HasDatabaseName("ix_public_applications_tenant_id_client_key")
                        .HasFilter("client_key IS NOT NULL");

                    b.ToTable("public_applications", (string)null);
                });

            modelBuilder.Entity("Recuro.Careers.Domain.Postings.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("experience");

                    b.Property<string>("Industry")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("industry");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("location");

                    b.Property<string>("LocationFilter")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("location_filter");

                    b.Property<string>("PostingId")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("posting_id");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("qualification");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("req_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("VisibleFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visible_from");

                    b.HasKey("Id")
                        .HasName("pk_job_postings");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_job_postings_tenant_id");

                    b.HasIndex("TenantId", "PostingId")
                        .IsUnique()
                        .HasDatabaseName("ix_job_postings_tenant_id_posting_id");

                    b.HasIndex("TenantId", "ReqId")
                        .IsUnique()
                        .HasDatabaseName("ix_job_postings_tenant_id_req_id");

                    b.HasIndex("TenantId", "VisibleFrom", "PostingId")
                        .HasDatabaseName("ix_job_postings_tenant_id_visible_from_posting_id")
                        .HasFilter("status = 'Published'");

                    b.ToTable("job_postings", (string)null);
                });

            modelBuilder.Entity("Recuro.Careers.Domain.Requisitions.SourcingGate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("req_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.Property<bool>("WasCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("was_cancelled");

                    b.HasKey("Id")
                        .HasName("pk_sourcing_gates");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sourcing_gates_tenant_id");

                    b.HasIndex("TenantId", "ReqId")
                        .IsUnique()
                        .HasDatabaseName("ix_sourcing_gates_tenant_id_req_id");

                    b.ToTable("sourcing_gates", (string)null);
                });

            modelBuilder.Entity("Recuro.Careers.Domain.Applications.PublicApplication", b =>
                {
                    b.OwnsMany("Recuro.Careers.Domain.Applications.GivenConsent", "Consents", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid")
                                .HasColumnName("application_id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("at");

                            b1.Property<string>("TextVersion")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("text_version");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("type");

                            b1.HasKey("Id")
                                .HasName("pk_public_application_consents");

                            b1.HasIndex("ApplicationId")
                                .HasDatabaseName("ix_public_application_consents_application_id");

                            b1.ToTable("public_application_consents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId")
                                .HasConstraintName("fk_public_application_consents_public_applications_application");
                        });

                    b.Navigation("Consents");
                });

            modelBuilder.Entity("Recuro.Careers.Domain.Postings.JobPosting", b =>
                {
                    b.OwnsMany("Recuro.Careers.Domain.Postings.PostingHistoryEntry", "History", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("action");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("at");

                            b1.Property<string>("By")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("by");

                            b1.Property<string>("ById")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("by_id");

                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uuid")
                                .HasColumnName("job_posting_id");

                            b1.Property<string>("Reason")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("reason");

                            b1.HasKey("Id")
                                .HasName("pk_job_posting_history");

                            b1.HasIndex("JobPostingId")
                                .HasDatabaseName("ix_job_posting_history_job_posting_id");

                            b1.ToTable("job_posting_history", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId")
                                .HasConstraintName("fk_job_posting_history_job_postings_job_posting_id");
                        });

                    b.OwnsMany("Recuro.Careers.Domain.Postings.PostingTag", "Tags", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("JobPostingId")
                                .HasColumnType("uuid")
                                .HasColumnName("job_posting_id");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("text");

                            b1.Property<string>("Tone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("tone");

                            b1.HasKey("Id")
                                .HasName("pk_job_posting_tags");

                            b1.HasIndex("JobPostingId")
                                .HasDatabaseName("ix_job_posting_tags_job_posting_id");

                            b1.ToTable("job_posting_tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JobPostingId")
                                .HasConstraintName("fk_job_posting_tags_job_postings_job_posting_id");
                        });

                    b.Navigation("History");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
