// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recuro.Candidate.Infrastructure.Persistence;

#nullable disable

namespace Recuro.Candidate.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CandidateDbContext))]
    [Migration("20261007204616_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("EventId", "Consumer")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("envelope");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at")
                        .HasFilter("processed_at IS NULL AND failed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.Candidate.Domain.Candidates.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentCtc")
                        .HasColumnType("text")
                        .HasColumnName("current_ctc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmailFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("email_fingerprint")
                        .IsFixedLength();

                    b.Property<string>("ExpectedCtc")
                        .HasColumnType("text")
                        .HasColumnName("expected_ctc");

                    b.Property<decimal>("ExperienceYears")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("experience_years");

                    b.Property<bool>("LegalHold")
                        .HasColumnType("boolean")
                        .HasColumnName("legal_hold");

                    b.Property<string>("LegalHoldReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("legal_hold_reason");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("NoticeDays")
                        .HasColumnType("integer")
                        .HasColumnName("notice_days");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PhoneFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("phone_fingerprint")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("PurgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purged_at");

                    b.Property<DateOnly?>("RetainUntil")
                        .HasColumnType("date")
                        .HasColumnName("retain_until");

                    b.Property<string>("RetentionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("retention_status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_candidates");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_candidates_tenant_id");

                    b.HasIndex("TenantId", "EmailFingerprint")
                        .HasDatabaseName("ix_candidates_tenant_id_email_fingerprint");

                    b.HasIndex("TenantId", "PhoneFingerprint")
                        .HasDatabaseName("ix_candidates_tenant_id_phone_fingerprint");

                    b.HasIndex("TenantId", "RetentionStatus", "RetainUntil")
                        .HasDatabaseName("ix_candidates_tenant_id_retention_status_retain_until");

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("Recuro.Candidate.Domain.Candidates.Candidate", b =>
                {
                    b.OwnsMany("Recuro.Candidate.Domain.Candidates.CandidateApplication", "Applications", b1 =>
                        {
                            b1.Property<Guid>("CandidateId")
                                .HasColumnType("uuid")
                                .HasColumnName("candidate_id");

                            b1.Property<string>("AppId")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("app_id");

                            b1.Property<string>("Outcome")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("outcome");

                            b1.Property<DateOnly?>("RetainUntil")
                                .HasColumnType("date")
                                .HasColumnName("retain_until");

                            b1.HasKey("CandidateId", "AppId")
                                .HasName("pk_candidate_applications");

                            b1.ToTable("candidate_applications", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CandidateId")
                                .HasConstraintName("fk_candidate_applications_candidates_candidate_id");
                        });

                    b.OwnsMany("Recuro.Candidate.Domain.Candidates.Consent", "Consents", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("at");

                            b1.Property<Guid>("CandidateId")
                                .HasColumnType("uuid")
                                .HasColumnName("candidate_id");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("source");

                            b1.Property<string>("TextVersion")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("text_version");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("type");

                            b1.HasKey("Id")
                                .HasName("pk_candidate_consents");

                            b1.HasIndex("CandidateId")
                                .HasDatabaseName("ix_candidate_consents_candidate_id");

                            b1.ToTable("candidate_consents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CandidateId")
                                .HasConstraintName("fk_candidate_consents_candidates_candidate_id");
                        });

                    b.OwnsOne("Recuro.Candidate.Domain.Candidates.ResumeFile", "Resume", b1 =>
                        {
                            b1.Property<Guid>("CandidateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("resume_content_type");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("resume_file_name");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("resume_size_bytes");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("resume_storage_key");

                            b1.Property<DateTimeOffset>("UploadedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("resume_uploaded_at");

                            b1.HasKey("CandidateId");

                            b1.ToTable("candidates");

                            b1.WithOwner()
                                .HasForeignKey("CandidateId")
                                .HasConstraintName("fk_candidates_candidates_id");
                        });

                    b.OwnsOne("Recuro.Candidate.Domain.Candidates.SourceAttribution", "Attribution", b1 =>
                        {
                            b1.Property<Guid>("CandidateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Channel")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("channel");

                            b1.Property<string>("ConsultantId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("consultant_id");

                            b1.Property<string>("ReferrerId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("referrer_id");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("source");

                            b1.Property<string>("SourceRef")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_ref");

                            b1.HasKey("CandidateId");

                            b1.ToTable("candidates");

                            b1.WithOwner()
                                .HasForeignKey("CandidateId")
                                .HasConstraintName("fk_candidates_candidates_id");
                        });

                    b.Navigation("Applications");

                    b.Navigation("Attribution")
                        .IsRequired();

                    b.Navigation("Consents");

                    b.Navigation("Resume");
                });
#pragma warning restore 612, 618
        }
    }
}
