using Microsoft.Extensions.Options;
using Recuro.Candidate.Application.Abstractions;
using Recuro.Candidate.Infrastructure.Pii;

namespace Recuro.Candidate.Infrastructure.Storage;

/// <summary>Bound from <c>ResumeStorage</c>.</summary>
public sealed class ResumeStorageOptions
{
    public const string SectionName = "ResumeStorage";

    /// <summary>Folder for CV files. In containers mount a volume here. Relative paths resolve from the working directory.</summary>
    public string RootPath { get; set; } = "data/resumes";
}

/// <summary>
/// CVs on local disk (free, no extra service), encrypted with the PII key so a copied disk reveals
/// nothing. A MinIO/S3 store can replace it behind <see cref="IResumeStore"/> without touching use cases.
/// </summary>
internal sealed class LocalResumeStore(IOptions<ResumeStorageOptions> options, IPiiCipher cipher) : IResumeStore
{
    private readonly string _root = Path.GetFullPath(options.Value.RootPath);

    public async Task SaveAsync(string key, Stream content, CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(content);
        var path = PathFor(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        using var buffer = new MemoryStream();
        await content.CopyToAsync(buffer, ct);
        await File.WriteAllBytesAsync(path, cipher.EncryptBytes(buffer.GetBuffer().AsSpan(0, (int)buffer.Length)), ct);
    }

    public async Task<Stream?> OpenAsync(string key, CancellationToken ct)
    {
        var path = PathFor(key);
        if (!File.Exists(path))
        {
            return null;
        }

        var sealedBytes = await File.ReadAllBytesAsync(path, ct);
        return new MemoryStream(cipher.DecryptBytes(sealedBytes), writable: false);
    }

    public Task DeleteAsync(string key, CancellationToken ct)
    {
        var path = PathFor(key);
        if (File.Exists(path))
        {
            File.Delete(path);
        }

        return Task.CompletedTask;
    }

    // Keys are generated by the service ({tenant}/{candidate}/{file}); still, never leave the root.
    private string PathFor(string key)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(key);
        var path = Path.GetFullPath(Path.Combine(_root, key));
        return path.StartsWith(_root + Path.DirectorySeparatorChar, StringComparison.Ordinal)
            ? path
            : throw new ArgumentException("Storage key escapes the storage root.", nameof(key));
    }
}
