// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recuro.Reporting.Infrastructure.Persistence;

#nullable disable

namespace Recuro.Reporting.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20261008184821_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("EventId", "Consumer")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("envelope");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at")
                        .HasFilter("processed_at IS NULL AND failed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.Reporting.Domain.Events.ProjectionCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence");

                    b.Property<string>("Projection")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("projection");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projection_checkpoints");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_projection_checkpoints_tenant_id");

                    b.HasIndex("TenantId", "Projection")
                        .IsUnique()
                        .HasDatabaseName("ix_projection_checkpoints_tenant_id_projection");

                    b.ToTable("projection_checkpoints", (string)null);
                });

            modelBuilder.Entity("Recuro.Reporting.Domain.Events.ReportEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Sequence"));

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_report_events");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_report_events_sequence");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_report_events_tenant_id");

                    b.HasIndex("TenantId", "Sequence")
                        .HasDatabaseName("ix_report_events_tenant_id_sequence");

                    b.ToTable("report_events", (string)null);
                });

            modelBuilder.Entity("Recuro.Reporting.Domain.Kpis.MetricDefinitionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Definitions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definitions");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_metric_definition_sets");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_metric_definition_sets_tenant_id");

                    b.HasIndex("TenantId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_metric_definition_sets_tenant_id_version");

                    b.ToTable("metric_definition_sets", (string)null);
                });

            modelBuilder.Entity("Recuro.Reporting.Domain.Projections.ApplicationFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset?>("BgvAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bgv_at");

                    b.Property<string>("CandidateId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("candidate_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FurthestStage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("furthest_stage");

                    b.Property<DateTimeOffset?>("InterviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("interviewed_at");

                    b.Property<DateTimeOffset?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateOnly?>("JoiningDate")
                        .HasColumnType("date")
                        .HasColumnName("joining_date");

                    b.Property<DateTimeOffset?>("OfferAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offer_accepted_at");

                    b.Property<DateTimeOffset?>("OfferDeclinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offer_declined_at");

                    b.Property<DateTimeOffset?>("OfferSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offer_sent_at");

                    b.Property<DateTimeOffset?>("OfferedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offered_at");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("ReqId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("req_id");

                    b.Property<DateTimeOffset?>("ScreenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("screened_at");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id")
                        .HasName("pk_application_facts");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_application_facts_tenant_id");

                    b.HasIndex("TenantId", "AppId")
                        .IsUnique()
                        .HasDatabaseName("ix_application_facts_tenant_id_app_id");

                    b.HasIndex("TenantId", "CandidateId")
                        .HasDatabaseName("ix_application_facts_tenant_id_candidate_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_application_facts_tenant_id_created_at");

                    b.HasIndex("TenantId", "OfferAcceptedAt")
                        .HasDatabaseName("ix_application_facts_tenant_id_offer_accepted_at");

                    b.ToTable("application_facts", (string)null);
                });

            modelBuilder.Entity("Recuro.Reporting.Domain.Projections.FeedbackFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("app_id");

                    b.Property<string>("InterviewId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("interview_id");

                    b.Property<string>("InterviewerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("interviewer_id");

                    b.Property<DateTimeOffset?>("OverdueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("overdue_at");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool?>("WithinSla")
                        .HasColumnType("boolean")
                        .HasColumnName("within_sla");

                    b.HasKey("Id")
                        .HasName("pk_feedback_facts");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_feedback_facts_tenant_id");

                    b.HasIndex("TenantId", "OverdueAt")
                        .HasDatabaseName("ix_feedback_facts_tenant_id_overdue_at");

                    b.HasIndex("TenantId", "SubmittedAt")
                        .HasDatabaseName("ix_feedback_facts_tenant_id_submitted_at");

                    b.HasIndex("TenantId", "InterviewId", "InterviewerId")
                        .IsUnique()
                        .HasDatabaseName("ix_feedback_facts_tenant_id_interview_id_interviewer_id");

                    b.ToTable("feedback_facts", (string)null);
                });

            modelBuilder.Entity("Recuro.Reporting.Domain.Projections.RequisitionFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("BudgetStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("budget_status");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Grade")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("grade");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("req_id");

                    b.Property<DateTimeOffset?>("SourcingUnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sourcing_unlocked_at");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_requisition_facts");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_requisition_facts_tenant_id");

                    b.HasIndex("TenantId", "ApprovedAt")
                        .HasDatabaseName("ix_requisition_facts_tenant_id_approved_at");

                    b.HasIndex("TenantId", "ReqId")
                        .IsUnique()
                        .HasDatabaseName("ix_requisition_facts_tenant_id_req_id");

                    b.ToTable("requisition_facts", (string)null);
                });

            modelBuilder.Entity("Recuro.Reporting.Domain.Reports.KpiSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cadence");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<string>("ComputedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("computed_by");

                    b.Property<int>("DefinitionsVersion")
                        .HasColumnType("integer")
                        .HasColumnName("definitions_version");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("hash")
                        .IsFixedLength();

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("period");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("UpToSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("up_to_sequence");

                    b.HasKey("Id")
                        .HasName("pk_kpi_snapshots");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_kpi_snapshots_tenant_id");

                    b.HasIndex("TenantId", "Period", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_kpi_snapshots_tenant_id_period_revision");

                    b.ToTable("kpi_snapshots", (string)null);
                });

            modelBuilder.Entity("Recuro.Reporting.Domain.Reports.RecruitmentCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date")
                        .HasColumnName("month");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recorded_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_recruitment_costs");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_recruitment_costs_tenant_id");

                    b.HasIndex("TenantId", "Month")
                        .HasDatabaseName("ix_recruitment_costs_tenant_id_month");

                    b.ToTable("recruitment_costs", (string)null);
                });

            modelBuilder.Entity("Recuro.Reporting.Domain.Reports.ReportPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cadence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Csv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("csv");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("Delivery")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("delivery");

                    b.Property<byte[]>("Pdf")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("pdf");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("period");

                    b.Property<Guid?>("ReadyEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("ready_event_id");

                    b.Property<string>("RecipientRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recipient_role");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("snapshot_hash")
                        .IsFixedLength();

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_report_packs");

                    b.HasIndex("ReadyEventId")
                        .HasDatabaseName("ix_report_packs_ready_event_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_report_packs_tenant_id");

                    b.HasIndex("TenantId", "Period", "Cadence", "RecipientRole")
                        .HasDatabaseName("ix_report_packs_tenant_id_period_cadence_recipient_role");

                    b.ToTable("report_packs", (string)null);
                });

            modelBuilder.Entity("Recuro.Reporting.Domain.Reports.ReportSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("MonthlyPack")
                        .HasColumnType("boolean")
                        .HasColumnName("monthly_pack");

                    b.Property<string>("MonthlyRecipientRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("monthly_recipient_role");

                    b.Property<bool>("QuarterlyPack")
                        .HasColumnType("boolean")
                        .HasColumnName("quarterly_pack");

                    b.Property<string>("QuarterlyRecipientRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("quarterly_recipient_role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_report_settings");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_report_settings_tenant_id");

                    b.ToTable("report_settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
