<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Recuro.Interview.Domain\Recuro.Interview.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\Recuro.BuildingBlocks.Application\Recuro.BuildingBlocks.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Recuro.Interview.UnitTests" />
    <InternalsVisibleTo Include="Recuro.Interview.IntegrationTests" />
  </ItemGroup>
</Project>
