<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Recuro.Requisition.Domain\Recuro.Requisition.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\Recuro.BuildingBlocks.Application\Recuro.BuildingBlocks.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Recuro.Requisition.UnitTests" />
    <InternalsVisibleTo Include="Recuro.Requisition.IntegrationTests" />
  </ItemGroup>
</Project>
