<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Recuro.Candidate.Application\Recuro.Candidate.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\Recuro.BuildingBlocks.Infrastructure\Recuro.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Recuro.Candidate.UnitTests" />
    <InternalsVisibleTo Include="Recuro.Candidate.IntegrationTests" />
  </ItemGroup>
</Project>
