// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recuro.Bgv.Infrastructure.Persistence;

#nullable disable

namespace Recuro.Bgv.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BgvDbContext))]
    partial class BgvDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recuro.Bgv.Domain.Cases.BgvCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("app_id");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("candidate_id");

                    b.Property<DateTimeOffset?>("ClearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cleared_at");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("grade");

                    b.Property<DateTimeOffset>("InitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("initiated_by");

                    b.Property<string>("MatrixVersionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("matrix_version_id");

                    b.Property<bool>("NeedsReassignment")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_reassignment");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("req_id");

                    b.PrimitiveCollection<string[]>("RoleFlags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("role_flags");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TatWorkingDays")
                        .HasColumnType("integer")
                        .HasColumnName("tat_working_days");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VendorCaseRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vendor_case_ref");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vendor_id");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vendor_name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_bgv_cases");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bgv_cases_tenant_id");

                    b.HasIndex("TenantId", "AppId")
                        .IsUnique()
                        .HasDatabaseName("ix_bgv_cases_tenant_id_app_id");

                    b.HasIndex("TenantId", "Status", "DueAt")
                        .HasDatabaseName("ix_bgv_cases_tenant_id_status_due_at");

                    b.HasIndex("TenantId", "VendorId", "Status")
                        .HasDatabaseName("ix_bgv_cases_tenant_id_vendor_id_status");

                    b.ToTable("bgv_cases", (string)null);
                });

            modelBuilder.Entity("Recuro.Bgv.Domain.Requests.BgvRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("app_id");

                    b.Property<bool>("AtBgv")
                        .HasColumnType("boolean")
                        .HasColumnName("at_bgv");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("candidate_id");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("req_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bgv_requests");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bgv_requests_tenant_id");

                    b.HasIndex("TenantId", "AppId")
                        .IsUnique()
                        .HasDatabaseName("ix_bgv_requests_tenant_id_app_id");

                    b.ToTable("bgv_requests", (string)null);
                });

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("EventId", "Consumer")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("envelope");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at")
                        .HasFilter("processed_at IS NULL AND failed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.Bgv.Domain.Cases.BgvCase", b =>
                {
                    b.OwnsOne("Recuro.Bgv.Domain.Cases.AdverseFinding", "Adverse", b1 =>
                        {
                            b1.Property<Guid>("BgvCaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("adverse_action");

                            b1.Property<string>("Check")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("adverse_check");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("adverse_description");

                            b1.Property<DateTimeOffset>("FlaggedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("adverse_flagged_at");

                            b1.Property<string>("FlaggedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("adverse_flagged_by");

                            b1.Property<Guid?>("WorkflowId")
                                .HasColumnType("uuid")
                                .HasColumnName("adverse_workflow_id");

                            b1.HasKey("BgvCaseId");

                            b1.ToTable("bgv_cases");

                            b1.WithOwner()
                                .HasForeignKey("BgvCaseId")
                                .HasConstraintName("fk_bgv_cases_bgv_cases_id");
                        });

                    b.OwnsOne("Recuro.Bgv.Domain.Cases.AdverseResolution", "Resolution", b1 =>
                        {
                            b1.Property<Guid>("BgvCaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("DecidedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("resolution_decided_at");

                            b1.Property<string>("DecidedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("resolution_decided_by");

                            b1.Property<string>("Outcome")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("resolution_outcome");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("resolution_reason");

                            b1.HasKey("BgvCaseId");

                            b1.ToTable("bgv_cases");

                            b1.WithOwner()
                                .HasForeignKey("BgvCaseId")
                                .HasConstraintName("fk_bgv_cases_bgv_cases_id");
                        });

                    b.OwnsOne("Recuro.Bgv.Domain.Cases.Consent", "Consent", b1 =>
                        {
                            b1.Property<Guid>("BgvCaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("consent_at");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("consent_source");

                            b1.Property<string>("TextVersion")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("consent_text_version");

                            b1.HasKey("BgvCaseId");

                            b1.ToTable("bgv_cases");

                            b1.WithOwner()
                                .HasForeignKey("BgvCaseId")
                                .HasConstraintName("fk_bgv_cases_bgv_cases_id");
                        });

                    b.OwnsMany("Recuro.Bgv.Domain.Cases.BgvCheck", "Checks", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("case_id");

                            b1.Property<DateOnly?>("Date")
                                .HasColumnType("date")
                                .HasColumnName("date");

                            b1.Property<string>("Detail")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("detail");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("label");

                            b1.Property<string>("Note")
                                .IsRequired()
                                .HasMaxLength(3000)
                                .HasColumnType("character varying(3000)")
                                .HasColumnName("note");

                            b1.Property<string>("SensitiveNote")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("sensitive_note");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("status");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("type");

                            b1.HasKey("Id")
                                .HasName("pk_bgv_checks");

                            b1.HasIndex("CaseId")
                                .HasDatabaseName("ix_bgv_checks_case_id");

                            b1.ToTable("bgv_checks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CaseId")
                                .HasConstraintName("fk_bgv_checks_bgv_cases_case_id");
                        });

                    b.Navigation("Adverse");

                    b.Navigation("Checks");

                    b.Navigation("Consent")
                        .IsRequired();

                    b.Navigation("Resolution");
                });
#pragma warning restore 612, 618
        }
    }
}
