using Recuro.Onboarding.Domain.Bgv;
using Recuro.Onboarding.Domain.Cases;
using Recuro.Onboarding.Domain.Rules;

namespace Recuro.Onboarding.Application.Abstractions;

/// <summary>Onboarding cases of the current tenant. Never returns another tenant's rows.</summary>
public interface IOnboardingCaseRepository
{
    /// <summary>Tracked: by case id, or the latest case for an application id.</summary>
    Task<OnboardingCase?> FindAsync(string caseOrAppId, CancellationToken ct);

    /// <summary>Tracked: the application's case that is still running (not cancelled), if any.</summary>
    Task<OnboardingCase?> FindRunningAsync(string appId, CancellationToken ct);

    /// <summary>Read-only, newest joining date last; <paramref name="status"/> null means every running case.</summary>
    Task<IReadOnlyList<OnboardingCase>> ListAsync(CaseStatus? status, int limit, CancellationToken ct);

    /// <summary>Tracked: running cases with a scheduled milestone due on or before <paramref name="today"/>.</summary>
    Task<IReadOnlyList<OnboardingCase>> ListWithDueMilestonesAsync(DateOnly today, int limit, CancellationToken ct);

    void Add(OnboardingCase onboardingCase);
}

public interface IBgvTrackRepository
{
    Task<BgvTrack?> GetAsync(string appId, CancellationToken ct);

    Task<IReadOnlyDictionary<string, BgvStatus>> StatusesAsync(IReadOnlyCollection<string> appIds, CancellationToken ct);

    void Add(BgvTrack track);
}

/// <summary>
/// The tenant's onboarding rules from Config (<c>resolve/matrices/onboarding</c>), or the FRD table
/// while Config has no onboarding matrix. Throws <see cref="DependencyUnavailableException"/> when
/// Config can't be reached, so an accepted offer is retried instead of planned from a guess.
/// </summary>
public interface IOnboardingRules
{
    Task<OnboardingTemplate> GetTemplateAsync(CancellationToken ct);
}

/// <summary>Working days on the tenant's business calendar (Config <c>resolve/working-days</c>).</summary>
public interface IWorkingDays
{
    /// <summary>The date <paramref name="days"/> working days before <paramref name="from"/>; 0 returns <paramref name="from"/>.</summary>
    Task<DateOnly> SubtractAsync(DateOnly from, int days, CancellationToken ct);

    /// <summary>The latest working day on or before <paramref name="day"/> (a touchpoint never lands on a holiday).</summary>
    Task<DateOnly> OnOrBeforeAsync(DateOnly day, CancellationToken ct) => SubtractAsync(day.AddDays(1), 1, ct);
}

/// <summary>What IT/Admin need to prepare Day 1 (RCU-ONB-001). Ids only: the adapter looks people up itself.</summary>
public sealed record ProvisioningRequest(Guid CaseId, string AppId, string ReqId, string CandidateId, DateOnly JoiningDate, string? ReportingManagerId);

/// <summary>
/// RCU-ONB-001 integration adapter for the IT/Admin ticketing system. One tenant may use a helpdesk,
/// another email; the use cases only see this interface.
/// </summary>
public interface IProvisioningAdapter
{
    /// <summary>Opens the Day-1 setup ticket and returns its reference. Idempotent per case.</summary>
    Task<string> OpenTicketAsync(ProvisioningRequest request, CancellationToken ct);

    /// <summary>Saga compensation: cancels a ticket for a hire that will not join.</summary>
    Task CancelTicketAsync(string ticketRef, CancellationToken ct);
}

/// <summary>§13 files. Keys are generated by the service and never come from a client.</summary>
public interface IDocumentStore
{
    Task SaveAsync(string key, Stream content, CancellationToken ct);

    Task<Stream?> OpenAsync(string key, CancellationToken ct);

    Task DeleteAsync(string key, CancellationToken ct);
}

/// <summary>The Candidate service, for the name on the confirmation letter. Null when unknown.</summary>
public interface ICandidateDirectory
{
    Task<string?> GetNameAsync(string candidateId, CancellationToken ct);
}

/// <summary>A person of the tenant as Identity knows them: user id, name and department key.</summary>
public sealed record Person(string Id, string Name, string Department);

/// <summary>
/// Identity's tenant-scoped people lookups (<c>GET /api/v1/identity/users/{id}</c> and
/// <c>?role=hod&amp;department=…</c>). Null when Identity has nobody; Identity not answering is
/// <see cref="DependencyUnavailableException"/>.
/// </summary>
public interface IPeopleDirectory
{
    Task<Person?> FindAsync(string userId, CancellationToken ct);

    Task<Person?> FindDepartmentHeadAsync(string department, CancellationToken ct);
}

/// <summary>RCU-ONB-005: renders the confirmation letter (white-label: names no company).</summary>
public interface IConfirmationLetterRenderer
{
    byte[] Render(OnboardingCase onboardingCase, ProbationDecision decision, string employeeName);
}

/// <summary>A service this one depends on did not answer. The API maps it to 503 so the client can retry.</summary>
public sealed class DependencyUnavailableException : Exception
{
    public DependencyUnavailableException()
    {
    }

    public DependencyUnavailableException(string message)
        : base(message)
    {
    }

    public DependencyUnavailableException(string message, Exception innerException)
        : base(message, innerException)
    {
    }
}
