<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Recuro.Audit.Application\Recuro.Audit.Application.csproj" />
    <ProjectReference Include="..\Recuro.Audit.Infrastructure\Recuro.Audit.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\Recuro.BuildingBlocks.Web\Recuro.BuildingBlocks.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
</Project>
