// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recuro.Employee.Infrastructure.Persistence;

#nullable disable

namespace Recuro.Employee.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20261008084306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("EventId", "Consumer")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("envelope");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at")
                        .HasFilter("processed_at IS NULL AND failed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.Employee.Domain.Ijp.IjpPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closes_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("department");

                    b.PrimitiveCollection<string[]>("EligibleGrades")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("eligible_grades");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grade");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("location");

                    b.Property<int>("MinTenureMonths")
                        .HasColumnType("integer")
                        .HasColumnName("min_tenure_months");

                    b.Property<DateTimeOffset>("OpensAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opens_at");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("req_id");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<bool>("Withdrawn")
                        .HasColumnType("boolean")
                        .HasColumnName("withdrawn");

                    b.HasKey("Id")
                        .HasName("pk_ijp_postings");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_ijp_postings_tenant_id");

                    b.HasIndex("TenantId", "ClosesAt")
                        .HasDatabaseName("ix_ijp_postings_tenant_id_closes_at")
                        .HasFilter("NOT withdrawn");

                    b.HasIndex("TenantId", "ReqId")
                        .IsUnique()
                        .HasDatabaseName("ix_ijp_postings_tenant_id_req_id");

                    b.ToTable("ijp_postings", (string)null);
                });

            modelBuilder.Entity("Recuro.Employee.Domain.Intake.IntakeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("app_id");

                    b.Property<bool>("CandidateCreatedHere")
                        .HasColumnType("boolean")
                        .HasColumnName("candidate_created_here");

                    b.Property<string>("CandidateId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("candidate_id");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("employee_id");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("employee_name");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("failure_code");

                    b.Property<string>("PipelineStage")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pipeline_stage");

                    b.Property<string>("Progress")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("progress");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("req_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.HasKey("Id")
                        .HasName("pk_intake_records");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_intake_records_tenant_id");

                    b.HasIndex("TenantId", "AppId")
                        .IsUnique()
                        .HasDatabaseName("ix_intake_records_tenant_id_app_id")
                        .HasFilter("app_id IS NOT NULL");

                    b.HasIndex("TenantId", "EmployeeId", "SubmittedAt")
                        .HasDatabaseName("ix_intake_records_tenant_id_employee_id_submitted_at");

                    b.ToTable("intake_records", (string)null);

                    b.HasDiscriminator<string>("kind").HasValue("IntakeRecord");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Recuro.Employee.Domain.Requisitions.SourcingGate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("req_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.Property<bool>("WasCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("was_cancelled");

                    b.HasKey("Id")
                        .HasName("pk_sourcing_gates");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sourcing_gates_tenant_id");

                    b.HasIndex("TenantId", "ReqId")
                        .IsUnique()
                        .HasDatabaseName("ix_sourcing_gates_tenant_id_req_id");

                    b.ToTable("sourcing_gates", (string)null);
                });

            modelBuilder.Entity("Recuro.Employee.Domain.Ijp.InternalApplication", b =>
                {
                    b.HasBaseType("Recuro.Employee.Domain.Intake.IntakeRecord");

                    b.Property<string>("DeclaredGrade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("declared_grade");

                    b.Property<DateOnly>("JoinedOn")
                        .HasColumnType("date")
                        .HasColumnName("joined_on");

                    b.Property<string>("PostingTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("posting_title");

                    b.HasDiscriminator().HasValue("ijp");
                });

            modelBuilder.Entity("Recuro.Employee.Domain.Referrals.Referral", b =>
                {
                    b.HasBaseType("Recuro.Employee.Domain.Intake.IntakeRecord");

                    b.Property<bool>("BonusEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("bonus_eligible");

                    b.Property<bool>("BonusPayable")
                        .HasColumnType("boolean")
                        .HasColumnName("bonus_payable");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("candidate_name");

                    b.Property<bool>("CoiAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("coi_accepted");

                    b.Property<DateTimeOffset>("CoiAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("coi_accepted_at");

                    b.Property<string>("DuplicateOf")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("duplicate_of");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("relationship");

                    b.HasDiscriminator().HasValue("referral");
                });
#pragma warning restore 612, 618
        }
    }
}
