// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recuro.Onboarding.Infrastructure.Persistence;

#nullable disable

namespace Recuro.Onboarding.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OnboardingDbContext))]
    [Migration("20261009081809_CaseDepartment")]
    partial class CaseDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("EventId", "Consumer")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("envelope");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at")
                        .HasFilter("processed_at IS NULL AND failed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.Onboarding.Domain.Bgv.BgvTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("app_id");

                    b.Property<string>("CaseId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("case_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bgv_tracks");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bgv_tracks_tenant_id");

                    b.HasIndex("TenantId", "AppId")
                        .IsUnique()
                        .HasDatabaseName("ix_bgv_tracks_tenant_id_app_id");

                    b.ToTable("bgv_tracks", (string)null);
                });

            modelBuilder.Entity("Recuro.Onboarding.Domain.Cases.OnboardingCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("app_id");

                    b.Property<string>("Buddy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("buddy");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("candidate_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset?>("Day1ReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("day1ready_at");

                    b.Property<string>("Department")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("department");

                    b.Property<DateTimeOffset?>("FileCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("file_completed_at");

                    b.Property<string>("FileCompletedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("file_completed_by");

                    b.Property<DateOnly>("JoiningDate")
                        .HasColumnType("date")
                        .HasColumnName("joining_date");

                    b.Property<string>("OfferId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("offer_id");

                    b.Property<int>("ProbationCycle")
                        .HasColumnType("integer")
                        .HasColumnName("probation_cycle");

                    b.Property<DateOnly>("ProbationEndsOn")
                        .HasColumnType("date")
                        .HasColumnName("probation_ends_on");

                    b.Property<int>("ProbationMonths")
                        .HasColumnType("integer")
                        .HasColumnName("probation_months");

                    b.Property<string>("ReportingManager")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reporting_manager");

                    b.Property<string>("ReportingManagerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reporting_manager_id");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("req_id");

                    b.Property<string>("RulesVersionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rules_version_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_onboarding_cases");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_onboarding_cases_tenant_id");

                    b.HasIndex("TenantId", "AppId")
                        .HasDatabaseName("ix_onboarding_cases_tenant_id_app_id");

                    b.HasIndex("TenantId", "Status", "JoiningDate")
                        .HasDatabaseName("ix_onboarding_cases_tenant_id_status_joining_date");

                    b.ToTable("onboarding_cases", (string)null);
                });

            modelBuilder.Entity("Recuro.Onboarding.Domain.Cases.OnboardingCase", b =>
                {
                    b.OwnsMany("Recuro.Onboarding.Domain.Cases.CaseDocument", "Documents", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("case_id");

                            b1.Property<string>("ContentType")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("content_type");

                            b1.Property<string>("FileName")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("label");

                            b1.Property<bool>("Mandatory")
                                .HasColumnType("boolean")
                                .HasColumnName("mandatory");

                            b1.Property<string>("Note")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("note");

                            b1.Property<int>("Position")
                                .HasColumnType("integer")
                                .HasColumnName("position");

                            b1.Property<DateTimeOffset?>("ReviewedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("reviewed_at");

                            b1.Property<string>("ReviewedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("reviewed_by");

                            b1.Property<long?>("Size")
                                .HasColumnType("bigint")
                                .HasColumnName("size");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("status");

                            b1.Property<string>("StorageKey")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("storage_key");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("type");

                            b1.Property<DateTimeOffset?>("UploadedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("uploaded_at");

                            b1.Property<string>("UploadedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("uploaded_by");

                            b1.HasKey("Id")
                                .HasName("pk_onboarding_documents");

                            b1.HasIndex("CaseId")
                                .HasDatabaseName("ix_onboarding_documents_case_id");

                            b1.ToTable("onboarding_documents", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CaseId")
                                .HasConstraintName("fk_onboarding_documents_onboarding_cases_case_id");
                        });

                    b.OwnsMany("Recuro.Onboarding.Domain.Cases.ChecklistItem", "Checklist", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("case_id");

                            b1.Property<bool>("Done")
                                .HasColumnType("boolean")
                                .HasColumnName("done");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("key");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("label");

                            b1.Property<int>("Position")
                                .HasColumnType("integer")
                                .HasColumnName("position");

                            b1.Property<string>("Remarks")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("remarks");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("updated_by");

                            b1.HasKey("Id")
                                .HasName("pk_onboarding_checklist_items");

                            b1.HasIndex("CaseId")
                                .HasDatabaseName("ix_onboarding_checklist_items_case_id");

                            b1.ToTable("onboarding_checklist_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CaseId")
                                .HasConstraintName("fk_onboarding_checklist_items_onboarding_cases_case_id");
                        });

                    b.OwnsMany("Recuro.Onboarding.Domain.Cases.Milestone", "Milestones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("CaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("case_id");

                            b1.Property<DateTimeOffset?>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at");

                            b1.Property<string>("CompletedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("completed_by");

                            b1.Property<int>("Cycle")
                                .HasColumnType("integer")
                                .HasColumnName("cycle");

                            b1.Property<DateOnly>("DueOn")
                                .HasColumnType("date")
                                .HasColumnName("due_on");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("kind");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("label");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasMaxLength(2200)
                                .HasColumnType("character varying(2200)")
                                .HasColumnName("notes");

                            b1.Property<string>("Phase")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phase");

                            b1.Property<DateTimeOffset?>("RaisedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("raised_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("status");

                            b1.Property<string>("TicketRef")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ticket_ref");

                            b1.HasKey("Id")
                                .HasName("pk_onboarding_milestones");

                            b1.HasIndex("CaseId")
                                .HasDatabaseName("ix_onboarding_milestones_case_id");

                            b1.HasIndex("Status", "DueOn")
                                .HasDatabaseName("ix_onboarding_milestones_status_due_on");

                            b1.ToTable("onboarding_milestones", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CaseId")
                                .HasConstraintName("fk_onboarding_milestones_onboarding_cases_case_id");
                        });

                    b.OwnsMany("Recuro.Onboarding.Domain.Cases.ProbationDecision", "Decisions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CaseId")
                                .HasColumnType("uuid")
                                .HasColumnName("case_id");

                            b1.Property<int>("Cycle")
                                .HasColumnType("integer")
                                .HasColumnName("cycle");

                            b1.Property<DateTimeOffset>("DecidedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("decided_at");

                            b1.Property<string>("DecidedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("decided_by");

                            b1.Property<string>("DecidedById")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("decided_by_id");

                            b1.Property<int?>("ExtendedByMonths")
                                .HasColumnType("integer")
                                .HasColumnName("extended_by_months");

                            b1.Property<DateOnly?>("NewProbationEnd")
                                .HasColumnType("date")
                                .HasColumnName("new_probation_end");

                            b1.Property<string>("Outcome")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("outcome");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("reason");

                            b1.HasKey("Id")
                                .HasName("pk_onboarding_probation_decisions");

                            b1.HasIndex("CaseId")
                                .HasDatabaseName("ix_onboarding_probation_decisions_case_id");

                            b1.ToTable("onboarding_probation_decisions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CaseId")
                                .HasConstraintName("fk_onboarding_probation_decisions_onboarding_cases_case_id");
                        });

                    b.Navigation("Checklist");

                    b.Navigation("Decisions");

                    b.Navigation("Documents");

                    b.Navigation("Milestones");
                });
#pragma warning restore 612, 618
        }
    }
}
