// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recuro.Pipeline.Infrastructure.Persistence;

#nullable disable

namespace Recuro.Pipeline.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PipelineDbContext))]
    [Migration("20261007230917_AddExpectedJoiningDate")]
    partial class AddExpectedJoiningDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("EventId", "Consumer")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("envelope");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at")
                        .HasFilter("processed_at IS NULL AND failed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.Pipeline.Domain.Applications.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("app_id");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("candidate_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("ExpectedJoiningDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_joining_date");

                    b.Property<DateTimeOffset?>("HeldAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("held_at");

                    b.Property<DateTimeOffset?>("HeldFromEnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("held_from_entered_at");

                    b.Property<string>("HeldFromStage")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("held_from_stage");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("note");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("req_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset>("StageEnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stage_entered_at");

                    b.Property<DateTimeOffset?>("TatBreachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tat_breached_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_applications_tenant_id");

                    b.HasIndex("Stage", "StageEnteredAt")
                        .HasDatabaseName("ix_applications_stage_stage_entered_at")
                        .HasFilter("tat_breached_at IS NULL");

                    b.HasIndex("TenantId", "AppId")
                        .IsUnique()
                        .HasDatabaseName("ix_applications_tenant_id_app_id");

                    b.HasIndex("TenantId", "ReqId", "CandidateId")
                        .HasDatabaseName("ix_applications_tenant_id_req_id_candidate_id");

                    b.HasIndex("TenantId", "ReqId", "Stage")
                        .HasDatabaseName("ix_applications_tenant_id_req_id_stage");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("Recuro.Pipeline.Domain.Requisitions.SourcingGate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("req_id");

                    b.Property<DateOnly?>("TargetClosure")
                        .HasColumnType("date")
                        .HasColumnName("target_closure");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("WasCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("was_cancelled");

                    b.HasKey("Id")
                        .HasName("pk_sourcing_gates");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sourcing_gates_tenant_id");

                    b.HasIndex("TenantId", "ReqId")
                        .IsUnique()
                        .HasDatabaseName("ix_sourcing_gates_tenant_id_req_id");

                    b.ToTable("sourcing_gates", (string)null);
                });

            modelBuilder.Entity("Recuro.Pipeline.Infrastructure.Persistence.ApplicationCounter", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<int>("Last")
                        .HasColumnType("integer")
                        .HasColumnName("last");

                    b.HasKey("TenantId", "Year")
                        .HasName("pk_application_counters");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_application_counters_tenant_id");

                    b.ToTable("application_counters", (string)null);
                });

            modelBuilder.Entity("Recuro.Pipeline.Domain.Applications.Application", b =>
                {
                    b.OwnsOne("Recuro.Pipeline.Domain.Applications.Rejection", "Rejection", b1 =>
                        {
                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("rejection_reason");

                            b1.Property<DateOnly>("RegretDueBy")
                                .HasColumnType("date")
                                .HasColumnName("rejection_regret_due_by");

                            b1.Property<DateOnly>("RetainUntil")
                                .HasColumnType("date")
                                .HasColumnName("rejection_retain_until");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("applications");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId")
                                .HasConstraintName("fk_applications_applications_id");
                        });

                    b.OwnsMany("Recuro.Pipeline.Domain.Applications.StageMove", "StageHistory", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid")
                                .HasColumnName("application_id");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("at");

                            b1.Property<string>("By")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("by");

                            b1.Property<string>("ById")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("by_id");

                            b1.Property<string>("From")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("from");

                            b1.Property<string>("To")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("to");

                            b1.HasKey("Id")
                                .HasName("pk_application_stage_moves");

                            b1.HasIndex("ApplicationId")
                                .HasDatabaseName("ix_application_stage_moves_application_id");

                            b1.ToTable("application_stage_moves", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId")
                                .HasConstraintName("fk_application_stage_moves_applications_application_id");
                        });

                    b.Navigation("Rejection");

                    b.Navigation("StageHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
