// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recuro.Offer.Infrastructure.Persistence;

#nullable disable

namespace Recuro.Offer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OfferDbContext))]
    partial class OfferDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("EventId", "Consumer")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("envelope");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at")
                        .HasFilter("processed_at IS NULL AND failed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Recuro.Offer.Domain.Applications.ApplicationTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("app_id");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("candidate_id");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("req_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset>("StageChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stage_changed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_application_tracks");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_application_tracks_tenant_id");

                    b.HasIndex("TenantId", "AppId")
                        .IsUnique()
                        .HasDatabaseName("ix_application_tracks_tenant_id_app_id");

                    b.ToTable("application_tracks", (string)null);
                });

            modelBuilder.Entity("Recuro.Offer.Domain.Bgv.BgvTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("app_id");

                    b.Property<string>("Blockers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("blockers");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gate");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bgv_tracks");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bgv_tracks_tenant_id");

                    b.HasIndex("TenantId", "AppId")
                        .IsUnique()
                        .HasDatabaseName("ix_bgv_tracks_tenant_id_app_id");

                    b.ToTable("bgv_tracks", (string)null);
                });

            modelBuilder.Entity("Recuro.Offer.Domain.Letters.OfferDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<int>("LetterVersion")
                        .HasColumnType("integer")
                        .HasColumnName("letter_version");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_offer_documents");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_offer_documents_tenant_id");

                    b.HasIndex("TenantId", "OfferId", "Kind", "LetterVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_offer_documents_tenant_id_offer_id_kind_letter_version");

                    b.ToTable("offer_documents", (string)null);
                });

            modelBuilder.Entity("Recuro.Offer.Domain.Offers.JobOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("app_id");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("candidate_id");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("candidate_name");

                    b.Property<int>("ChaseCount")
                        .HasColumnType("integer")
                        .HasColumnName("chase_count");

                    b.Property<TimeSpan>("ChaseEvery")
                        .HasColumnType("interval")
                        .HasColumnName("chase_every");

                    b.Property<bool>("Conditional")
                        .HasColumnType("boolean")
                        .HasColumnName("conditional");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("designation");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("grade");

                    b.Property<DateOnly>("JoiningDate")
                        .HasColumnType("date")
                        .HasColumnName("joining_date");

                    b.Property<int>("LetterVersion")
                        .HasColumnType("integer")
                        .HasColumnName("letter_version");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset?>("NextChaseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_chase_at");

                    b.Property<int>("ProbationMonths")
                        .HasColumnType("integer")
                        .HasColumnName("probation_months");

                    b.Property<string>("ReportingManager")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reporting_manager");

                    b.Property<string>("ReqId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("req_id");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Route")
                        .HasColumnType("jsonb")
                        .HasColumnName("route");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("WorkflowInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_instance_id");

                    b.Property<string>("_trail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("trail");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Band", "Recuro.Offer.Domain.Offers.JobOffer.Band#PayBand", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Max")
                                .HasPrecision(10, 1)
                                .HasColumnType("numeric(10,1)")
                                .HasColumnName("band_max");

                            b1.Property<decimal>("Min")
                                .HasPrecision(10, 1)
                                .HasColumnType("numeric(10,1)")
                                .HasColumnName("band_min");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Components", "Recuro.Offer.Domain.Offers.JobOffer.Components#CtcComponents", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Benefits")
                                .HasPrecision(10, 1)
                                .HasColumnType("numeric(10,1)")
                                .HasColumnName("ctc_benefits");

                            b1.Property<decimal>("Fixed")
                                .HasPrecision(10, 1)
                                .HasColumnType("numeric(10,1)")
                                .HasColumnName("ctc_fixed");

                            b1.Property<decimal>("Variable")
                                .HasPrecision(10, 1)
                                .HasColumnType("numeric(10,1)")
                                .HasColumnName("ctc_variable");
                        });

                    b.HasKey("Id")
                        .HasName("pk_offers");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_offers_tenant_id");

                    b.HasIndex("WorkflowInstanceId")
                        .HasDatabaseName("ix_offers_workflow_instance_id");

                    b.HasIndex("State", "NextChaseAt")
                        .HasDatabaseName("ix_offers_state_next_chase_at");

                    b.HasIndex("TenantId", "AppId")
                        .HasDatabaseName("ix_offers_tenant_id_app_id");

                    b.HasIndex("TenantId", "CandidateId")
                        .HasDatabaseName("ix_offers_tenant_id_candidate_id");

                    b.HasIndex("TenantId", "State")
                        .HasDatabaseName("ix_offers_tenant_id_state");

                    b.ToTable("offers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
