using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Options;
using Recuro.Onboarding.Application.Abstractions;

namespace Recuro.Onboarding.Infrastructure.Storage;

/// <summary>
/// Bound from <c>DocumentStorage</c>. Keys are 32-byte AES keys in base64. Production keys come from
/// environment variables or a free vault (Infisical, OpenBao), never from a committed file. Rotate by
/// adding a key and switching <see cref="ActiveKeyId"/>: each file names the key that sealed it.
/// </summary>
public sealed class DocumentStorageOptions
{
    public const string SectionName = "DocumentStorage";

    /// <summary>Folder for §13 files. In containers mount a volume here. Relative paths resolve from the working directory.</summary>
    public string RootPath { get; set; } = "data/onboarding-documents";

    public string ActiveKeyId { get; set; } = string.Empty;

    public Dictionary<string, string> Keys { get; set; } = [];
}

/// <summary>
/// §13 files (ID proofs, bank details) on local disk, sealed with AES-256-GCM (BNFR-3), so a copied disk
/// reveals nothing. A MinIO/S3 store can replace it behind <see cref="IDocumentStore"/>.
/// </summary>
internal sealed class LocalDocumentStore : IDocumentStore
{
    private const int NonceSize = 12;
    private const int TagSize = 16;
    private readonly string _root;
    private readonly Dictionary<string, byte[]> _keys;
    private readonly string _activeKeyId;

    public LocalDocumentStore(IOptions<DocumentStorageOptions> options)
    {
        var value = options.Value;
        _root = Path.GetFullPath(value.RootPath);
        _keys = value.Keys.ToDictionary(k => k.Key, k => Convert.FromBase64String(k.Value), StringComparer.Ordinal);
        _activeKeyId = value.ActiveKeyId;
        if (!_keys.TryGetValue(_activeKeyId, out var active) || active.Length != 32)
        {
            throw new InvalidOperationException($"DocumentStorage:Keys has no 32-byte key named '{_activeKeyId}'.");
        }
    }

    public async Task SaveAsync(string key, Stream content, CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(content);
        var path = PathFor(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        using var buffer = new MemoryStream();
        await content.CopyToAsync(buffer, ct);
        await File.WriteAllBytesAsync(path, Seal(buffer.GetBuffer().AsSpan(0, (int)buffer.Length)), ct);
    }

    public async Task<Stream?> OpenAsync(string key, CancellationToken ct)
    {
        var path = PathFor(key);
        if (!File.Exists(path))
        {
            return null;
        }

        return new MemoryStream(Open(await File.ReadAllBytesAsync(path, ct)), writable: false);
    }

    public Task DeleteAsync(string key, CancellationToken ct)
    {
        var path = PathFor(key);
        if (File.Exists(path))
        {
            File.Delete(path);
        }

        return Task.CompletedTask;
    }

    // Header: key-id length (1 byte), key id, then nonce | tag | ciphertext.
    private byte[] Seal(ReadOnlySpan<byte> plaintext)
    {
        var keyId = Encoding.UTF8.GetBytes(_activeKeyId);
        var output = new byte[1 + keyId.Length + NonceSize + TagSize + plaintext.Length];
        output[0] = checked((byte)keyId.Length);
        keyId.CopyTo(output, 1);
        var body = output.AsSpan(1 + keyId.Length);
        var nonce = body[..NonceSize];
        RandomNumberGenerator.Fill(nonce);
        using var aes = new AesGcm(_keys[_activeKeyId], TagSize);
        aes.Encrypt(nonce, plaintext, body[(NonceSize + TagSize)..], body.Slice(NonceSize, TagSize));
        return output;
    }

    private byte[] Open(ReadOnlySpan<byte> sealedBytes)
    {
        if (sealedBytes.Length < 1 || sealedBytes.Length < 1 + sealedBytes[0] + NonceSize + TagSize)
        {
            throw new CryptographicException("Value is not an encrypted Recuro file.");
        }

        var keyIdLength = sealedBytes[0];
        var keyId = Encoding.UTF8.GetString(sealedBytes.Slice(1, keyIdLength));
        var key = _keys.TryGetValue(keyId, out var found) ? found : throw new CryptographicException($"Encryption key '{keyId}' is not configured.");
        var body = sealedBytes[(1 + keyIdLength)..];
        var plaintext = new byte[body.Length - NonceSize - TagSize];
        using var aes = new AesGcm(key, TagSize);
        aes.Decrypt(body[..NonceSize], body[(NonceSize + TagSize)..], body.Slice(NonceSize, TagSize), plaintext);
        return plaintext;
    }

    // Keys are generated by the service ({tenant}/{case}/{type}-{id}); still, never leave the root.
    private string PathFor(string key)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(key);
        var path = Path.GetFullPath(Path.Combine(_root, key));
        return path.StartsWith(_root + Path.DirectorySeparatorChar, StringComparison.Ordinal)
            ? path
            : throw new ArgumentException("Storage key escapes the storage root.", nameof(key));
    }
}
