// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recuro.Admin.Infrastructure.Persistence;

#nullable disable

namespace Recuro.Admin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20261007182658_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recuro.Admin.Domain.Screens.ScreenDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanDisable")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DefaultSubtitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DefaultTitle")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("screen_definitions", (string)null);
                });

            modelBuilder.Entity("Recuro.Admin.Domain.Screens.TenantScreenConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ScreenKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ScreenKey")
                        .IsUnique();

                    b.ToTable("tenant_screen_configurations", (string)null);
                });

            modelBuilder.Entity("Recuro.Admin.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ThemePresetKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("CustomDomain")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Recuro.Admin.Domain.Theming.ThemePreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("theme_presets", (string)null);
                });

            modelBuilder.Entity("Recuro.Admin.Domain.Screens.ScreenDefinition", b =>
                {
                    b.OwnsMany("Recuro.Admin.Domain.Screens.FieldDefinition", "Fields", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("DataType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("DefaultLabel")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<bool>("DefaultRequired")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsLocked")
                                .HasColumnType("boolean");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)");

                            b1.Property<Guid>("ScreenDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("ScreenDefinitionId");

                            b1.ToTable("field_definitions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ScreenDefinitionId");
                        });

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Recuro.Admin.Domain.Screens.TenantScreenConfiguration", b =>
                {
                    b.HasOne("Recuro.Admin.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Recuro.Admin.Domain.Screens.TenantFieldSetting", "Fields", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("FieldKey")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsVisible")
                                .HasColumnType("boolean");

                            b1.Property<string>("Label")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("integer");

                            b1.Property<Guid>("TenantScreenConfigurationId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TenantScreenConfigurationId");

                            b1.ToTable("tenant_field_settings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TenantScreenConfigurationId");
                        });

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Recuro.Admin.Domain.Theming.ThemePreset", b =>
                {
                    b.OwnsOne("Recuro.Admin.Domain.Theming.ThemePalette", "Dark", b1 =>
                        {
                            b1.Property<Guid>("ThemePresetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Accent")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("dark_accent");

                            b1.Property<string>("Background")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("dark_background");

                            b1.Property<string>("Primary")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("dark_primary");

                            b1.Property<string>("Secondary")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("dark_secondary");

                            b1.Property<string>("Surface")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("dark_surface");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("dark_text");

                            b1.HasKey("ThemePresetId");

                            b1.ToTable("theme_presets");

                            b1.WithOwner()
                                .HasForeignKey("ThemePresetId");
                        });

                    b.OwnsOne("Recuro.Admin.Domain.Theming.ThemePalette", "Light", b1 =>
                        {
                            b1.Property<Guid>("ThemePresetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Accent")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("light_accent");

                            b1.Property<string>("Background")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("light_background");

                            b1.Property<string>("Primary")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("light_primary");

                            b1.Property<string>("Secondary")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("light_secondary");

                            b1.Property<string>("Surface")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("light_surface");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("light_text");

                            b1.HasKey("ThemePresetId");

                            b1.ToTable("theme_presets");

                            b1.WithOwner()
                                .HasForeignKey("ThemePresetId");
                        });

                    b.Navigation("Dark")
                        .IsRequired();

                    b.Navigation("Light")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
